spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: root
#    password: qr30tfbq
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
server:
  port: 8080
  servlet:
    # 指定接口全局api
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-not-delete-value: 0 #不删除值
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

